#Configuration for Player Profile (Spigot) HNMC (Survival)

settings:
  servername: ""
  plugin-enable: false
  sync-interval: 3 #in seconds

mysql:
  host: "localhost"
  port: 3306
  database: ""
  username: ""
  password: ""
  use-ssl: false